# Generated by Django 4.2.7 on 2026-09-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starfish', '0007_project_agent_config_project_agent_log_run_agent_advice_run_agent_diagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, unique=True)),
                ('size', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
