# Generated by Django 4.2.7 on 2026-09-27 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starfish', '0008_storedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=40, unique=True)),
                ('bucket_hz', models.IntegerField()),
                ('sequence', models.IntegerField()),
                ('path', models.CharField(max_length=500)),
                ('size', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('batch', models.IntegerField()),
                ('task_seq', models.IntegerField()),
                ('round_seq', models.IntegerField()),
                ('source_version', models.CharField(max_length=200)),
                ('eval_report', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='starfish.modelversion')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='starfish.project')),
            ],
            options={
                'ordering': ['bucket_hz', '-sequence'],
                'unique_together': {('bucket_hz', 'sequence')},
            },
        ),
    ]
