# Generated by Django 4.2.7 on 2026-09-27 06:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('starfish', '0009_modelversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tasks',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='run',
            name='artifacts',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='run',
            name='logs',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='run',
            name='middle_artifacts',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='run',
            name='site_uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='run',
            name='tasks',
            field=models.JSONField(default=list),
        ),
    ]
