# Generated by Django 4.2.7 on 2026-09-27 06:43

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('starfish', '0010_callable_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Failed'), (1, 'Pending Failed'), (2, 'Standby'), (3, 'Preparing'), (4, 'Running'), (5, 'Pending Success'), (6, 'Pending Aggregating'), (7, 'Aggregating'), (8, 'Success'), (9, 'Sitting Out')], default=2, protected=True),
        ),
    ]
